name: belhisfirm-sampo

services:
  # Sampo UI - Client
  client:
    build:
      context: ./client
      target: client-prod
    image: sampo-ui-client:prod
    container_name: sampo-ui-client-prod
    network_mode: host
    environment:
      API_URL: ${API_URL}

  # Sampo UI - Server
  server:
    build:
      context: ./server
      target: server-build
    image: sampo-ui-server:prod
    container_name: sampo-ui-server-prod
    network_mode: host
    volumes:
      - ./sampo/configs:/app/configs