name: belhisfirm-vkg

services:

  # Ontop Virtual Knowledge Graph
  vkg-scob:
    image: ghcr.io/ghentcdh/belhisfirm-ontop:latest
    container_name: belhisfirm-scob-vkg
    restart: unless-stopped
    environment:
      ONTOP_CORS_ALLOWED_ORIGINS: "*"
      ONTOP_LAZY_INIT: "true"
      ONTOP_DEV_MODE: "false"
      DB_URL: ${DB_URL_SCOB}
      DB_USER: ${DB_USER_SCOB}
      DB_PASSWORD: ${DB_PASSWORD_SCOB}
      DB_DRIVER: ${DB_DRIVER_SCOB}
    network_mode: host
    healthcheck:
      test: [ "CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/" ]
      interval: 30s
      timeout: 10s
      retries: 3
