name: belhisfirm-sampo

services:
  # Sampo UI - Client
  client:
    image: ghcr.io/ghentcdh/sampo-ui-client:latest
    container_name: sampo-ui-client-prod
    network_mode: host
    environment:
      API_URL: ${API_URL}

  # Sampo UI - Server
  server:
    image: ghcr.io/ghentcdh/sampo-ui-server:latest
    container_name: sampo-ui-server-prod
    network_mode: host
    volumes:
      - ./sampo/configs:/app/configs