name: belhisfirm-vkg

services:

  # Ontop Virtual Knowledge Graph
  vkg-scob:
    image: ontop/ontop:latest
    container_name: belhisfirm-scob-vkg
    restart: unless-stopped
    volumes:
      - ./vkg/input:/opt/ontop/input
      - ./vkg/jdbc:/opt/ontop/jdbc
    environment:
      ONTOP_ONTOLOGY_FILE: /opt/ontop/input/ontology.ttl
      ONTOP_MAPPING_FILE: /opt/ontop/input/mappings.ttl
      ONTOP_PROPERTIES_FILE: /opt/ontop/input/ontop.properties
      ONTOP_CORS_ALLOWED_ORIGINS: "*"
      ONTOP_LAZY_INIT: "true"
      ONTOP_DEV_MODE: "false"
      DB_URL: ${DB_URL_SCOB}
      DB_USER: ${DB_USER_SCOB}
      DB_PASSWORD: ${DB_PASSWORD_SCOB}
      DB_DRIVER: ${DB_DRIVER_SCOB}
    network_mode: host
    healthcheck:
      test: [ "CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/" ]
      interval: 30s
      timeout: 10s
      retries: 3