version: '3.8'

# Development override - mounts source code for live editing
# Usage: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

services:
  db:
    ports:
      - "5432:5432"
    environment:
      # More verbose logging for development
      POSTGRES_LOG_STATEMENT: all

  vkg:
    environment:
      # Enable development mode - auto-reload on config changes
      ONTOP_DEV_MODE: "true"
    volumes:
      # Mount configs for live editing
      - ./vkg/input:/opt/ontop/input:ro
      - ./vkg/jdbc:/opt/ontop/jdbc:ro

  sampo:
    # Mount source code for hot-reload
    volumes:
      - ./sampo/src:/app/src:ro
      - ./sampo/public:/app/public:ro
    environment:
      NODE_ENV: development
    # Override command if needed for dev server
    # command: npm run dev


  dataseeder:
    environment:
      # Smaller dataset for faster development
      SEED_COMPANIES: 0
      SEED_PERSONS: 0
      SEED_BATCH_SIZE: 100
